[workspace]
members = ["shared", "app/src-tauri"]
resolver = "2"

[workspace.package]
version = "1.0.0"
authors = ["Carlo Corradini"]
edition = "2021"
rust-version = "1.70"
publish = false


[profile.dev.build-override]
debug = true
